scalar DateTime

type Query {
    shows(titleFilter: String, yearFilter: Int): [Show!]!
    showById(id: ID!): Show
    media(titleFilter: String): [Media!]!
    search(term: String!): [SearchResult!]!
    reviewsSince(since: DateTime!): [Review!]!
}

type Mutation {
    addShow(input: AddShowInput!): Show!
}

type Subscription {
    showAdded: Show!
}

interface Media {
    id: ID!
    title: String!
    releaseYear: Int
}

type Show implements Media {
    id: ID!
    title: String!
    releaseYear: Int
    seasons: Int
    reviews: [Review!]
}

type Movie implements Media {
    id: ID!
    title: String!
    releaseYear: Int
    runtimeMinutes: Int
}

type Review {
    username: String!
    starScore: Int!
    submittedDate: DateTime
}

union SearchResult = Show | Movie | Review

input AddShowInput {
    title: String!
    releaseYear: Int
    seasons: Int
}